# Common configuration.
AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*.rb
    - config/**/*
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - app/api/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table
  EnforcedLastArgumentHashStyle: ignore_implicit
